### ISSUE TITLE
Name of the output file

### ISSUE THREAD

**Issue by rladlb** [juliensalinas/torrengo#9]
Hi,

Thanks for this great tool.

Is it possible to save the output file with the name of the search ?

For exemple :
torrengo -s ygg watchmen les gardiens

in watchmen.les.gardiens.torrent rather than download_torrent?id=xxxx

**Comment by juliensalinas** [comment]
Hi @rladlb I agree that the current `download_torrent?id=xxxx` format is not very user friendly.
It seems to me that the problem with your solution is that `watchmen.les.gardiens.torrent` is not a unique id and there's a high risk of collision. For example I would be very likely to make multiple searches for "watchmen les gardiens" and download them all in order to see which torrent would start downloading first...
Maybe a concatenation of `watchmen.les.gardiens.torrent` and the timestamp would make it? Like `watchmen.les.gardiens.20200128164425.torrent`? What do you think?

**Comment by rladlb** [comment]
yes, you right.
It's better doing a concatenation with the timestamp or the id of the torrent

**Comment by juliensalinas** [comment]
@rladlb I just implemented the feature, can you confirm it's working on your side?

**Comment by rladlb** [comment]
Yes it's ok for me
tks :)
